### PR TITLE
Cleaned up some code and added null-checks.

### PR DESCRIPTION
**Pull request by DuckBoss**

### CODE REVIEW

**Review by williambl — APPROVED** [review]
Looks good. I'll merge it now. Thanks for this!

**Comment by williambl** [comment]
By the way, how did you find this? I don't remember linking to this repo anywhere.

**Comment by williambl** [comment]
Your [name generator](https://github.com/DuckBoss/NamePlaceGen-Unity) is really cool, btw. I'll probably use it at some point in the future, once I add NPCs with dialogue.

**Comment by DuckBoss** [comment]
Oh I found it be searching for the most recently updated repositories on github relating to Unity3D. At the time you just happened to update one of your repos so I decided to take a look. 
Glad to know you liked the Name Generator tool, its original intention was for NPCs so glad it worked out for you. I suggest you pre-generate the names in your games though. Otherwise it may cause a temporary spike in your framerate if you generate during a dialogue (it varies per person/computer).

**Comment by williambl** [comment]
I see. Thanks!

**Pull request merged**
